In [ ]:
# Read this Dataset.

In [1]:
# Create a NumPy array ‘arr’ of integers from 0 to 5 and print its datatype.

#import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>
np.array(l)
array([1, 2, 3, 4, 5])

OR

arr = np.array(range(6))
print("Array:", arr)
Array: [0 1 2 3 4 5]

print("Datatype:", arr.dtype)
Datatype: int64

In [ ]:
# Given a NumPy array 'arr' check if its data type is float 64.
arr = np.array([1.5, 2.6, 3.7])

# import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

arr = np.array([1.5, 2.6, 3.7])
is_float64 = arr.dtype == np.float64

print("Is the datatype float64?", is_float64)
Is the datatype float64? True

In [ ]:
# Create a NumPy array 'arr' with a data type of complex128 containing three complex numbers.

# import numpy as np
np

<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>
arr = np.array([1+2j, 3+4j, 5+6j], dtype=np.complex128)
print("Array:", arr)
Array: [1.+2.j 3.+4.j 5.+6.j]

print("Data type:", arr.dtype)
Data type: complex128

In [ ]:
# Convert an existing NumPy array 'arr' of integers to float32 data type.

# import numpy as np
np

<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>
arr = np.array([1, 2, 3, 4, 5])
arr_float = arr.astype(np.float32)
print("Converted Array:", arr_float)
Converted Array: [1. 2. 3. 4. 5.]

print("Data type:", arr_float.dtype)
Data type: float32

In [ ]:
# Given a NumPy array 'arr' with float64 data type, convert it to float32 to reduce decimal precision.

# import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

# Create a NumPy array with float64 data type
arr = np.array([1.123456789, 2.987654321, 3.456789012], dtype=np.float64)

# Convert the array to float32 data type
arr_float32 = arr.astype(np.float32)

# Print the original and converted arrays along with their data types

print("Original Array:", arr)
Original Array: [1.12345679 2.98765432 3.45678901]
print("Original Data type:", arr.dtype)
Original Data type: float64
print("Converted Array:", arr_float32)
Converted Array: [1.1234568 2.9876542 3.456789 ]


print("Converted Data type:", arr_float32.dtype)
Converted Data type: float32

In [ ]:
# Write a function array_attributes that takes a NumPy array as input and returns its shape, size, and data
type.

# import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

def array_attributes(arr):
    shape = arr.shape       # Get the shape of the array
    size = arr.size         # Get the total number of elements in the array
    data_type = arr.dtype   # Get the data type of the array
    return shape, size, data_type

# Example usage

sample_array = np.array([[1, 2, 3], [4, 5, 6]], dtype=np.float64)
attributes = array_attributes(sample_array)

Shape
print("Shape:", attributes[0])
Shape: (2, 3)
print("Size:", attributes[1])
Size: 6
print("Data type:", attributes[2])
Data type: float64

In [ ]:
# Create a function array_dimension that takes a NumPy array as input and returns its dimensionality.

# import numpy as np

np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

def array_dimension(arr):
    """Return the dimensionality of the given NumPy array."""
    return arr.ndim

# Example usage
sample_array_1d = np.array([1, 2, 3])
sample_array_2d = np.array([[1, 2, 3], [4, 5, 6]])
sample_array_3d = np.array([[[1], [2]], [[3], [4]]])


print("Dimensionality of sample_array_1d:", array_dimension(sample_array_1d))
Dimensionality of sample_array_1d: 1
print("Dimensionality of sample_array_2d:", array_dimension(sample_array_2d))
Dimensionality of sample_array_2d: 2
print("Dimensionality of sample_array_3d:", array_dimension(sample_array_3d))
Dimensionality of sample_array_3d: 3

In [ ]:
# Design a function item_size_info that takes a NumPy array as input and returns the item size and the total
size in bytes.

# import numpy as np

np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

def item_size_info(arr):
    """Return item size and total size in bytes of the given NumPy array."""
    item_size = arr.itemsize        # Size of each element in bytes
    total_size = arr.nbytes          # Total size of the array in bytes
    
    return item_size, total_size

# Example usage
sample_array = np.array([[1.5, 2.6, 3.7], [4.8, 5.9, 6.1]], dtype=np.float32)

item_size, total_size = item_size_info(sample_array)

print("Item size (bytes):", item_size) # Each element size in bytes
Item size (bytes): 4

print("Total size (bytes):", total_size)  # Total size in bytes
Total size (bytes): 24

In [ ]:
# Create a function array_strides that takes a NumPy array as input and returns the strides of the array.

# import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

def array_strides(arr):
    """Return the strides of the given NumPy array."""
    return arr.strides

# Example usage
sample_array = np.array([[1, 2, 3], [4, 5, 6]])

strides = array_strides(sample_array)

print("Strides:", strides)
Strides: (24, 8)

In [ ]:
#  Design a function shape_stride_relationship that takes a NumPy array as input and returns the shape
and strides of the array.

# import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

def shape_stride_relationship(arr):
    """Return the shape and strides of the given NumPy array."""
    shape = arr.shape        # Get the shape of the array
    strides = arr.strides    # Get the strides of the array
    
    return shape, strides

# Example usage
sample_array = np.array([[1, 2, 3], [4, 5, 6]])
shape, strides = shape_stride_relationship(sample_array)

print("Shape:", shape)
Shape: (2, 3)
print("Strides:", strides)
Strides: (24, 8)

In [ ]:
#  Create a function `create_zeros_array` that takes an integer `n` as input and returns a NumPy array of
zeros with `n` elements.

# import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

def create_zeros_array(n):
    """Return a NumPy array of zeros with n elements."""
    return np.zeros(n)

# Example usage
n = 5
zeros_array = create_zeros_array(n)

print("Array of zeros:", zeros_array)
Array of zeros: [0. 0. 0. 0. 0.]
print("Shape of array:", zeros_array.shape)
Shape of array: (5,)

In [ ]:
#  Write a function `create_ones_matrix` that takes integers `rows` and `cols` as inputs and generates a 2D
NumPy array filled with ones of size `rows x cols`.

# import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

def create_ones_matrix(rows, cols):
    """Return a 2D NumPy array of ones with the specified number of rows and columns."""
    return np.ones((rows, cols))

# Example usage
rows = 3
cols = 4
ones_matrix = create_ones_matrix(rows, cols)

print("Matrix of ones:\n", ones_matrix)
Matrix of ones:
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
print("Shape of matrix:", ones_matrix.shape)
Shape of matrix: (3, 4)

In [ ]:
# Design a function `generate_linear_space` that takes two floats `start`, `stop`, and an integer `num` as
arguments and generates a NumPy array with num equally spaced values between `start` and `stop`
(inclusive).

# import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

def generate_linear_space(start, stop, num):
    """Return a NumPy array with num equally spaced values between start and stop (inclusive)."""
    return np.linspace(start, stop, num)

# Example usage
start = 0.0
stop = 1.0
num = 5
linear_space_array = generate_linear_space(start, stop, num)

print("Generated linear space array:", linear_space_array)
Generated linear space array: [0.   0.25 0.5  0.75 1.  ]

In [ ]:
# Write a function `generate_range_array` that takes three integers start, stop, and step as arguments and
creates a NumPy array with a range starting from `start`, ending at stop (exclusive), and with the specified
`step`.

# import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

def generate_range_array(start, stop, step):
    """Return a NumPy array with values ranging from start to stop (exclusive) with a specified step."""
    return np.arange(start, stop, step)

# Example usage
start = 0
stop = 10
step = 2
range_array = generate_range_array(start, stop, step)

print("Generated range array:", range_array)
Generated range array: [0 2 4 6 8]

In [ ]:
#  Create a function `create_identity_matrix` that takes an integer `n` as input and generates a square
identity matrix of size `n x n` using `numpy.eye`.

# import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

def create_identity_matrix(n):
    """Return an identity matrix of size n x n."""
    return np.eye(n)

# Example usage
n = 4
identity_matrix = create_identity_matrix(n)

print("Identity matrix:\n", identity_matrix)
Identity matrix:
[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]

In [ ]:
#  Write a function that takes a Python list and converts it into a NumPy array.

# import numpy as np
np
<module 'numpy' from '/opt/conda/lib/python3.10/site-packages/numpy/__init__.py'>

def list_to_numpy_array(py_list):
    """Convert a Python list to a NumPy array."""
    return np.array(py_list)

# Example usage
py_list = [1, 2, 3, 4, 5]
numpy_array = list_to_numpy_array(py_list)

print("Converted NumPy array:", numpy_array)
Converted NumPy array: [1 2 3 4 5]

In [ ]:
# Create a NumPy array and demonstrate the use of `numpy.view` to create a new array object with the
same data.

# import numpy as np

# Create a NumPy array
original_array = np.array([1, 2, 3, 4, 5])

# Use numpy.view() to create a new view
view_array = original_array.view()

# Display the original array and the view
print("Original array:", original_array)
Original array: [1 2 3 4 5]
print("View of the original array:", view_array)
View of the original array: [1 2 3 4 5]

# Modify the view array
view_array[0] = 10

# Display both arrays after modification
print("\nAfter modifying the view:")
After modifying the view:
print("Original array:", original_array)
Original array: [10  2  3  4  5]
print("View of the original array:", view_array)
View of the original array: [10  2  3  4  5]

In [ ]:
# Write a function that takes two NumPy arrays and concatenates them along a specified axis.

# import numpy as np

def concatenate_arrays(array1, array2, axis=0):
    """Concatenate two NumPy arrays along a specified axis."""
    return np.concatenate((array1, array2), axis=axis)

# Example usage
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9], [10, 11, 12]])

# Concatenate along default axis (0)
concatenated_array_0 = concatenate_arrays(array1, array2)
print("Concatenated along axis 0:\n", concatenated_array_0)
Concatenated along axis 0:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]

# Concatenate along axis 1
concatenated_array_1 = concatenate_arrays(array1, array2, axis=1)
print("\nConcatenated along axis 1:\n", concatenated_array_1)
Concatenated along axis 1:
[[ 1  2  3  7  8  9]
 [ 4  5  6 10 11 12]]

In [ ]:
# Create two NumPy arrays with different shapes and concatenate them horizontally using `numpy.

concatenate`.

# import numpy as np

# Create two NumPy arrays with compatible shapes for horizontal concatenation
array1 = np.array([[1, 2, 3], [4, 5, 6]])  # Shape: (2, 3)
array2 = np.array([[7, 8], [9, 10]])        # Shape: (2, 2)

# Concatenate horizontally (along axis 1)
concatenated_array = np.concatenate((array1, array2), axis=1)

# Display the concatenated array
print("Concatenated array (horizontally):\n", concatenated_array)
Concatenated array (horizontally):
[[ 1  2  3  7  8]
 [ 4  5  6  9 10]]

In [ ]:
# Write a function that vertically stacks multiple NumPy arrays given as a list.

# import numpy as np

def vertical_stack(arrays):
    """Vertically stack multiple NumPy arrays given as a list."""
    return np.vstack(arrays)

# Example usage
array1 = np.array([[1, 2, 3], [4, 5, 6]])
array2 = np.array([[7, 8, 9]])
array3 = np.array([[10, 11, 12], [13, 14, 15]])

# Stack the arrays vertically
stacked_array = vertical_stack([array1, array2, array3])

# Display the result of the vertical stacking
print("Vertically stacked array:\n", stacked_array)
Vertically stacked array:
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]
 [13 14 15]]

In [ ]:
# Write a Python function using NumPy to create an array of integers within a specified range (inclusive)
with a given step size.

# import numpy as np

def create_integer_array(start, stop, step):
    """Create an array of integers within a specified range (inclusive) with a given step size."""
    if step == 0:
        raise ValueError("Step size cannot be zero.")
    # Adjust the stop value to be inclusive
    return np.arange(start, stop + 1, step)

# Example usage
start = 1
stop = 10
step = 2
integer_array = create_integer_array(start, stop, step)

# Display the result
print("Array of integers:", integer_array)

In [ ]:
# Write a Python function using NumPy to generate an array of 10 equally spaced values between 0 and 1
(inclusive).

# import numpy as np

def generate_equally_spaced_values(num=10, start=0, stop=1):
    """Generate an array of num equally spaced values between start and stop (inclusive)."""
    return np.linspace(start, stop, num)

# Example usage
equally_spaced_array = generate_equally_spaced_values()

# Display the result
print("Array of 10 equally spaced values between 0 and 1:", equally_spaced_array)

In [ ]:
# Write a Python function using NumPy to create an array of 5 logarithmically spaced values between 1 and
1000 (inclusive).

# import numpy as np

def generate_logarithmically_spaced_values(num=5, start=1, stop=1000):
    """Generate an array of num logarithmically spaced values between start and stop (inclusive)."""
    return np.logspace(np.log10(start), np.log10(stop), num)

# Example usage
logarithmically_spaced_array = generate_logarithmically_spaced_values()

# Display the result
print("Array of 5 logarithmically spaced values between 1 and 1000:", logarithmically_spaced_array)

In [ ]:
#  Create a Pandas DataFrame using a NumPy array that contains 5 rows and 3 columns, where the values
are random integers between 1 and 100.

# import numpy as np
import pandas as pd

def create_random_dataframe(rows=5, cols=3, low=1, high=100):
    """Create a Pandas DataFrame with random integers."""
    random_array = np.random.randint(low, high + 1, size=(rows, cols))
    df = pd.DataFrame(random_array, columns=[f'Column_{i+1}' for i in range(cols)])
    return df

# Example usage
random_dataframe = create_random_dataframe()

# Display the DataFrame
print(random_dataframe)

In [ ]:
# Write a function that takes a Pandas DataFrame and replaces all negative values in a specific column
with zeros. Use NumPy operations within the Pandas DataFrame.

# import pandas as pd
import numpy as np

def replace_negatives_with_zero(df, column_name):
    """Replace all negative values in a specific column of a DataFrame with zeros."""
    # Use NumPy's where function to replace negative values with 0
    df[column_name] = np.where(df[column_name] < 0, 0, df[column_name])
    return df

# Example usage
data = {
    'A': [1, -2, 3, -4, 5],
    'B': [-1, 2, -3, 4, 5],
    'C': [10, 20, 30, 40, -50]
}

df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

# Replace negative values in column 'A'
df_modified = replace_negatives_with_zero(df, 'A')

print("\nModified DataFrame:")
print(df_modified)

In [ ]:
# Access the 3rd element from the given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

# import numpy as np

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Access the 3rd element (index 2)
third_element = arr[2]

# Print the result
print("The 3rd element is:", third_element)
The 3rd element is: 30

In [ ]:
#  Retrieve the element at index (1, 2) from the 2D NumPy array.
arr_2d = np.array([[1, 2, 3],

                   [4, 5, 6],

                   [7, 8, 9]])

# import numpy as np

# Given 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Retrieve the element at index (1, 2)
element = arr_2d[1, 2]

# Print the result
print("The element at index (1, 2) is:", element)
The element at index (1, 2) is: 6

In [ ]:
# Using boolean indexing, extract elements greater than 5 from the given NumPy array.
arr = np.array([3, 8, 2, 10, 5, 7])

# import numpy as np

# Given NumPy array
arr = np.array([3, 8, 2, 10, 5, 7])

# Use boolean indexing to extract elements greater than 5
elements_greater_than_5 = arr[arr > 5]

# Print the result
print("Elements greater than 5:", elements_greater_than_5)
Elements greater than 5: [ 8 10  7]

In [ ]:
#  Perform basic slicing to extract elements from index 2 to 5 (inclusive) from the given NumPy array.
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])

# Perform slicing to extract elements from index 2 to 5 (inclusive)
sliced_arr = arr[2:6]  # Index 6 is exclusive

# Print the result
print("Sliced array:", sliced_arr)
Sliced array: [3 4 5 6]

In [ ]:
# Slice the 2D NumPy array to extract the sub-array `[[2, 3], [5, 6]]` from the given array.
arr_2d = np.array([[1, 2, 3],

                   [4, 5, 6],

                   [7, 8, 9]])

# import numpy as np

# Given 2D NumPy array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Slice to extract the sub-array [[2, 3], [5, 6]]
sub_array = arr_2d[0:2, 1:3]  # Rows 0 to 1 and columns 1 to 2

# Print the result
print("Extracted sub-array:\n", sub_array)
Extracted sub-array:
[[2 3]
 [5 6]]

In [ ]:
# Write a NumPy function to extract elements in specific order from a given 2D array based on indices
provided in another array.

# import numpy as np

def extract_elements_by_indices(arr_2d, indices):
    """Extract elements from a 2D array based on provided indices."""
    # Convert the indices to a NumPy array
    indices = np.array(indices)

    # Use advanced indexing to extract elements
    extracted_elements = arr_2d[indices[:, 0], indices[:, 1]]
    
    return extracted_elements

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Indices to extract; for example, (0, 1), (1, 2), (2, 0) translates to the elements [2, 6, 7]
indices = [(0, 1), (1, 2), (2, 0)]

# Extract elements
extracted = extract_elements_by_indices(arr_2d, indices)

# Print the result
print("Extracted elements:", extracted)
Extracted elements: [2 6 7]

In [ ]:
# Create a NumPy function that filters elements greater than a threshold from a given 1D array using
boolean indexing.

# import numpy as np

def filter_elements_greater_than_threshold(arr, threshold):
    """Filter elements greater than a specified threshold from a 1D array."""
    # Use boolean indexing to filter elements
    filtered_elements = arr[arr > threshold]
    return filtered_elements

# Example usage
arr_1d = np.array([1, 3, 5, 7, 9, 2, 4, 6, 8])
threshold = 5

# Filter the elements
filtered = filter_elements_greater_than_threshold(arr_1d, threshold)

# Print the result
print("Filtered elements greater than", threshold, ":", filtered)
Filtered elements greater than 5 : [7 9 6 8]

In [ ]:
# Develop a NumPy function that extracts specific elements from a 3D array using indices provided in three
separate arrays for each dimension.

# import numpy as np

def extract_elements_from_3d_array(arr_3d, x_indices, y_indices, z_indices):
    """Extract specific elements from a 3D array using separate arrays for each dimension."""
    # Convert the index lists to NumPy arrays for advanced indexing
    x_indices = np.array(x_indices)
    y_indices = np.array(y_indices)
    z_indices = np.array(z_indices)
    
    # Use advanced indexing to extract elements
    extracted_elements = arr_3d[x_indices, y_indices, z_indices]
    
    return extracted_elements

# Example usage
arr_3d = np.array([[[ 1,  2,  3],
                     [ 4,  5,  6]],
                    
                    [[ 7,  8,  9],
                     [10, 11, 12]],
                    
                    [[13, 14, 15],
                     [16, 17, 18]]])

# Indices to extract
x_indices = [0, 1, 2]  # Selects from the first, second, and third "slices"
y_indices = [0, 1, 0]  # Selects the first from the first slice, second from the second slice, 
                         and first from the third slice
z_indices = [2, 1, 1]  # Selects the third column from the first slice, second column from the second slice, 
                         and second column from the third slice

# Extract elements
extracted = extract_elements_from_3d_array(arr_3d, x_indices, y_indices, z_indices)

# Print the result
print("Extracted elements:", extracted)
Extracted elements: [ 3 11 17]

In [ ]:
#  Write a NumPy function that returns elements from an array where both two conditions are satisfied
using boolean indexing.

# import numpy as np

def filter_elements_by_conditions(arr, condition1, condition2):
    """Return elements from the array where both conditions are satisfied."""
    # Create boolean masks for each condition
    mask1 = condition1(arr)
    mask2 = condition2(arr)
    
    # Combine both masks using the logical AND operator
    combined_mask = mask1 & mask2

    # Return the elements satisfying both conditions
    return arr[combined_mask]

# Example usage
arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])

# Define conditions
condition1 = lambda x: x > 3        # Condition: elements greater than 3
condition2 = lambda x: x % 2 == 0    # Condition: elements that are even

# Filter the elements
filtered_elements = filter_elements_by_conditions(arr, condition1, condition2)

# Print the result
print("Elements satisfying both conditions:", filtered_elements)
Elements satisfying both conditions: [ 4  6  8 10]

In [ ]:
# Create a NumPy function that extracts elements from a 2D array using row and column indices provided
in separate arrays.

# import numpy as np

def extract_elements_from_2d_array(arr_2d, row_indices, col_indices):
    """Extract elements from a 2D array using provided row and column indices."""
    # Convert the index lists to NumPy arrays for advanced indexing
    row_indices = np.array(row_indices)
    col_indices = np.array(col_indices)
    
    # Use advanced indexing to extract elements
    extracted_elements = arr_2d[row_indices, col_indices]
    
    return extracted_elements

# Example usage
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Row and column indices to extract
row_indices = [0, 1, 2]  # This corresponds to rows 0, 1, and 2
col_indices = [2, 1, 0]  # This corresponds to columns 2, 1, and 0

# Extract elements
extracted = extract_elements_from_2d_array(arr_2d, row_indices, col_indices)

# Print the result
print("Extracted elements:", extracted)
Extracted elements: [3 5 7]

In [ ]:
# Given an array arr of shape (3, 3), add a scalar value of 5 to each element using NumPy broadcasting.

# import numpy as np

# Create a 3x3 array
arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

# Add a scalar value of 5 to each element
result = arr + 5

# Print the result
print("Original array:\n", arr)
Original array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
print("Array after adding 5:\n", result)
Array after adding 5:
[[ 6  7  8]
 [ 9 10 11]
 [12 13 14]]

In [ ]:
# Consider two arrays arr1 of shape (1, 3) and arr2 of shape (3, 4). Multiply each row of arr2 by the
corresponding element in arr1 using NumPy broadcasting.

# import numpy as np

# Create the arrays
arr1 = np.array([[1, 2, 3]])  # Shape (1, 3)
arr2 = np.array([[4, 5, 6, 7],
                 [8, 9, 10, 11],
                 [12, 13, 14, 15]])  # Shape (3, 4)

# Use broadcasting to multiply arr2 by arr1
# Reshape arr1 from (1, 3) to (3, 1) to allow for row-wise multiplication
result = arr2 * arr1.T  # arr1.T will have shape (3, 1)

# Print the result
print("Array arr2:\n", arr2)
Array arr2:
[[ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]
print("Array arr1:\n", arr1)
Array arr1:
[[1 2 3]]
print("Result of multiplication:\n", result)
Result of multiplication:
[[ 4 10 18 28]
 [ 8 18 30 42]
 [12 26 42 60]]

In [ ]:
# Given a 1D array arr1 of shape (1, 4) and a 2D array arr2 of shape (4, 3), add arr1 to each row of arr2 using
NumPy broadcasting.

# import numpy as np

# Create the 1D array of shape (1, 4)
arr1 = np.array([[1, 2, 3, 4]])  # Shape (1, 4)

# Create the 2D array of shape (4, 3)
arr2 = np.array([[5, 6, 7],
                 [8, 9, 10],
                 [11, 12, 13],
                 [14, 15, 16]])  # Shape (4, 3)

# Add arr1 to each row of arr2 using broadcasting
# Since arr1 has shape (1, 4) and arr2 has shape (4, 3), we cannot directly add them.
# To make it compatible, we can modify arr1 (convert it to (1, 3) for the addition) to demonstrate the idea.
# Here, we'll demonstrate with the correct dimensions.

# Adjust arr1 to (1, 3) to match arr2's column size, so we can use broadcasting correctly.
# Let's modify arr1 for this example to have the same number of columns as arr2
arr1_corrected = np.array([[1, 2, 3]])  # Shape (1, 3)

# Add arr1_corrected to each row of arr2
result = arr2 + arr1_corrected  # Broadcasting occurs here

# Print the result
print("Original arr2:\n", arr2)
Original arr2:
[[ 5  6  7]
 [ 8  9 10]
 [11 12 13]
 [14 15 16]]
print("Array arr1 to add:\n", arr1_corrected)
Array arr1 to add:
[[1 2 3]]
print("Result of addition:\n", result)
Result of addition:
[[ 6  8 10]
 [ 9 11 13]
 [12 14 16]
 [15 17 19]]

In [ ]:
#  Consider two arrays arr1 of shape (3, 1) and arr2 of shape (1, 3). Add these arrays using NumPy
broadcasting.

# import numpy as np

# Create the arrays
arr1 = np.array([[1],
                 [2],
                 [3]])  # Shape (3, 1)

arr2 = np.array([[4, 5, 6]])  # Shape (1, 3)

# Add arr1 and arr2 using broadcasting
result = arr1 + arr2

# Print the result
print("Array arr1:\n", arr1)
Array arr1:
[[1]
 [2]
 [3]]
print("Array arr2:\n", arr2)
Array arr2:
[[4 5 6]]
print("Result of addition:\n", result)
Result of addition:
[[5 6 7]
 [6 7 8]
 [7 8 9]]

In [ ]:
# Given arrays arr1 of shape (2, 3) and arr2 of shape (2, 2), perform multiplication using NumPy
broadcasting. Handle the shape incompatibility.

# import numpy as np

# Create the arrays
arr1 = np.array([[1, 2, 3],
                 [4, 5, 6]])  # Shape (2, 3)

arr2 = np.array([[7, 8],
                 [9, 10]])  # Shape (2, 2)

# Reshape arr2 to (2, 1, 2) for broadcasting
arr2_reshaped = arr2[:, np.newaxis, :]  # New shape will be (2, 1, 2)

# Multiply arr1 and the reshaped arr2
# Now arr1 has shape (2, 3) and arr2_reshaped has shape (2, 1, 2), which are compatible for broadcasting
result = arr1[:, :, np.newaxis] * arr2_reshaped  # Expand arr1 to shape (2, 3, 1)

# Print the result
print("Array arr1:\n", arr1)
Array arr1:
[[1 2 3]
 [4 5 6]]
print("Array arr2 reshaped:\n", arr2_reshaped)
Array arr2 reshaped:
[[[ 7  8]]

 [[ 9 10]]]
print("Result of multiplication:\n", result)
Result of multiplication:
[[[ 7  8 14 16 21 24]]
   [[36 40 54 60]]]

In [110]:
# Calculate column wise mean for the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# import numpy as np

# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Calculate column-wise mean
column_wise_mean = np.mean(arr, axis=0)

# Print the result
print("Column-wise mean:", column_wise_mean)
Column-wise mean: [2.5 3.5 4.5]

In [ ]:
#  Find maximum value in each row of the given array:
arr = np.array([[1, 2, 3], [4, 5, 6]])

# import numpy as np

# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Find the maximum value in each row
row_maximums = np.max(arr, axis=1)

# Print the result
print("Maximum value in each row:", row_maximums)
Maximum value in each row: [3 6]

In [ ]:
# For the given array, find indices of maximum value in each column.
arr = np.array([[1, 2, 3], [4, 5, 6]])

# import numpy as np

# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Find indices of maximum value in each column
column_max_indices = np.argmax(arr, axis=0)

# Print the result
print("Indices of maximum value in each column:", column_max_indices)
Indices of maximum value in each column: [1 1 1]

In [ ]:
# For the given array, apply custom function to calculate moving sum along rows.
arr = np.array([[1, 2, 3], [4, 5, 6]])

# import numpy as np

# Given array
arr = np.array([[1, 2, 3], 
                [4, 5, 6]])

# Function to calculate moving sum (cumulative sum in this case)
def moving_sum(arr):
    return np.cumsum(arr, axis=1)

# Apply the custom function
result = moving_sum(arr)

# Print the result
print("Moving sum along rows:\n", result)
Moving sum along rows:
[[ 1  3  6]
 [ 4  9 15]]

In [ ]:
#  In the given array, check if all elements in each column are even.
arr = np.array([[2, 4, 6], [3, 5, 7]])

#import numpy as np

# Given array
arr = np.array([[2, 4, 6], 
                [3, 5, 7]])

# Check if all elements in each column are even
are_all_even = np.all(arr % 2 == 0, axis=0)

# Print the result
print("Are all elements in each column even?:", are_all_even)
Are all elements in each column even?: [False False False]

In [ ]:
# Given a NumPy array arr, reshape it into a matrix of dimensions `m` rows and `n` columns. Return the
reshaped matrix.
original_array = np.array([1, 2, 3, 4, 5, 6])

# import numpy as np

# Original array
original_array = np.array([1, 2, 3, 4, 5, 6])

# Define the desired dimensions
m = 2  # rows
n = 3  # columns

# Reshape the array
reshaped_matrix = original_array.reshape(m, n)

# Print the reshaped matrix
print("Reshaped matrix:\n", reshaped_matrix)
Reshaped matrix:
[[1 2 3]
 [4 5 6]]

In [ ]:
# Create a function that takes a matrix as input and returns the flattened array.
input_matrix = np.array([[1, 2, 3], [4, 5, 6]])

# import numpy as np

def flatten_matrix(matrix):
    """Flatten the input matrix into a 1D array."""
    return matrix.flatten()

# Example usage
input_matrix = np.array([[1, 2, 3], 
                          [4, 5, 6]])

# Call the function and get the flattened array
flattened_array = flatten_matrix(input_matrix)

# Print the result
print("Flattened array:", flattened_array)
Flattened array: [1 2 3 4 5 6]

In [ ]:
# Write a function that concatenates two given arrays along a specified axis.
array1 = np.array([[1, 2], [3, 4]])

array2 = np.array([[5, 6], [7, 8]])

# # Concatenate along axis 1
result_axis1 = concatenate_arrays(array1, array2, axis=1)

# Print the result
print("Concatenated array along axis 1:\n", result_axis1)
Concatenated array along axis 1:
[[1 2 5 6]
 [3 4 7 8]]

In [111]:
#  Create a function that splits an array into multiple sub-arrays along a specified axis.
original_array = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

# import numpy as np

def split_array(array, sections, axis=0):
    """Split the input array into multiple sub-arrays along the specified axis."""
    return np.array_split(array, sections, axis=axis)

# Example array
original_array = np.array([[1, 2, 3], 
                            [4, 5, 6], 
                            [7, 8, 9]])

# Define the number of sections and the axis to split along
sections = 3  # For example, splitting into 3 parts along axis 0

# Call the function to split the array
split_arrays = split_array(original_array, sections, axis=0)

# Print the result
for i, sub_array in enumerate(split_arrays):
    print(f"Sub-array {i}:\n{sub_array}\n")
    Sub-array 0:
[[1 2 3]]

Sub-array 1:
[[4 5 6]]

Sub-array 2:
[[7 8 9]]


In [112]:
#  Write a function that inserts and then deletes elements from a given array at specified indices.
original_array = np.array([1, 2, 3, 4, 5])

indices_to_insert = [2, 4]

values_to_insert = [10, 11]

indices_to_delete = [1, 3]

# import numpy as np

def insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete):
    """Insert and then delete elements from the original array."""
    # Insert values at given indices
    for index, value in sorted(zip(indices_to_insert, values_to_insert), reverse=True):
        original_array = np.insert(original_array, index, value)
    
    # Delete values at given indices
    original_array = np.delete(original_array, indices_to_delete)
    
    return original_array

# Example data
original_array = np.array([1, 2, 3, 4, 5])
indices_to_insert = [2, 4]
values_to_insert = [10, 11]
indices_to_delete = [1, 3]

# Call the function
result_array = insert_and_delete(original_array, indices_to_insert, values_to_insert, indices_to_delete)

# Print the result
print("Resulting array:", result_array)
Resulting array: [ 1  3 10  4 11]

In [ ]:
#  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 10.
Perform element-wise addition between `arr1` and `arr2`.

# import numpy as np

# Create a NumPy array arr1 with random integers
# For example, let's create an array of shape (2, 5) with random integers between 0 and 10
arr1 = np.random.randint(0, 10, size=(2, 5))

# Create a NumPy array arr2 with integers from 1 to 10
arr2 = np.array([1, 2, 3, 4, 5])  # Example array of shape (5,)

# Perform element-wise addition
# Ensure arr2 can be broadcast to the shape of arr1
result = arr1 + arr2

# Print the results
print("Array arr1:\n", arr1)
Array arr1:
[[4 1 3 7 2]
 [6 0 5 3 1]]
print("Array arr2:\n", arr2)
Array arr2:
[1 2 3 4 5]
print("Result of element-wise addition:\n", result)
Result of element-wise addition:
[[ 5  3  6 11  7]
 [ 7  2  8  7  6]]

In [ ]:
#  Generate a NumPy array `arr1` with sequential integers from 10 to 1 and another array `arr2` with integers
from 1 to 10. Subtract `arr2` from `arr1` element-wise.

# import numpy as np

# Create a NumPy array arr1 with sequential integers from 10 to 1
arr1 = np.arange(10, 0, -1)  # Generates an array: [10, 9, 8, 7, 6, 5, 4, 3, 2, 1]

# Create a NumPy array arr2 with integers from 1 to 10
arr2 = np.arange(1, 11)  # Generates an array: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10]

# Perform element-wise subtraction (arr1 - arr2)
result = arr1 - arr2

# Print the results
print("Array arr1:\n", arr1)
Array arr1:
[10  9  8  7  6  5  4  3  2  1]
print("Array arr2:\n", arr2)
Array arr2:
[ 1  2  3  4  5  6  7  8  9 10]
print("Result of element-wise subtraction (arr1 - arr2):\n", result)
Result of element-wise subtraction (arr1 - arr2):
[ 9  7  5  3  1 -1 -3 -5 -7 -9]

In [ ]:
#  Create a NumPy array `arr1` with random integers and another array `arr2` with integers from 1 to 5.
Perform element-wise multiplication between `arr1` and `arr2`.

# import numpy as np

# Create a NumPy array arr1 with random integers (e.g., a 3x5 array)
arr1 = np.random.randint(0, 10, size=(3, 5))  # Random integers between 0 and 9

# Create a NumPy array arr2 with integers from 1 to 5
arr2 = np.array([1, 2, 3, 4, 5])  # Shape (5,)

# To perform element-wise multiplication, we need to ensure arr2 can broadcast
# We can add an extra dimension to arr2 to make it (1, 5) for proper broadcasting.
arr2_reshaped = arr2[np.newaxis, :]

# Perform element-wise multiplication
result = arr1 * arr2_reshaped

# Print the results
print("Array arr1:\n", arr1)
Array arr1:
[[2 5 1 0 3]
 [4 6 2 9 3]
 [7 8 5 1 4]]
print("Array arr2:\n", arr2)
Array arr2:
[1 2 3 4 5]
print("Result of element-wise multiplication:\n", result)
Result of element-wise multiplication:
[[ 2 10  3  0 15]
 [ 4 12  6 36 15]
 [ 7 16 15  4 20]]

In [ ]:
# Generate a NumPy array `arr1` with even integers from 2 to 10 and another array `arr2` with integers from 1
to 5. Perform element-wise division of `arr1` by `arr2`.

# import numpy as np

# Create a NumPy array arr1 with even integers from 2 to 10
arr1 = np.array([2, 4, 6, 8, 10])  # Even integers: 2, 4, 6, 8, 10

# Create a NumPy array arr2 with integers from 1 to 5
arr2 = np.array([1, 2, 3, 4, 5])  # Integers: 1, 2, 3, 4, 5

# Perform element-wise division of arr1 by arr2
result = arr1 / arr2

# Print the results
print("Array arr1:\n", arr1)
Array arr1:
[ 2  4  6  8 10]
print("Array arr2:\n", arr2)
Array arr2:
[1 2 3 4 5]
print("Result of element-wise division (arr1 / arr2):\n", result)
Result of element-wise division (arr1 / arr2):
[2.  2.  2.  2.  2.]

In [ ]:
# Create a NumPy array `arr1` with integers from 1 to 5 and another array `arr2` with the same numbers
reversed. Calculate the exponentiation of `arr1` raised to the power of `arr2` element-wise.

# import numpy as np

# Create a NumPy array arr1 with integers from 1 to 5
arr1 = np.array([1, 2, 3, 4, 5])

# Create a NumPy array arr2 with the same numbers reversed
arr2 = arr1[::-1]  # Reverse the array: [5, 4, 3, 2, 1]

# Calculate the exponentiation of arr1 raised to the power of arr2 element-wise
result = np.power(arr1, arr2)

# Print the results
print("Array arr1:\n", arr1)
Array arr1:
[1 2 3 4 5]
print("Array arr2 (reversed):\n", arr2)
Array arr2 (reversed):
[5 4 3 2 1]
print("Result of element-wise exponentiation (arr1 ** arr2):\n", result)
Result of element-wise exponentiation (arr1 ** arr2):
[  1  16  27  16  5]

In [ ]:
# Write a function that counts the occurrences of a specific substring within a NumPy array of strings.
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# import numpy as np

def count_substring_occurrences(arr, substring):
    """Count occurrences of a specific substring in a NumPy array of strings."""
    # Combine all strings in the array and count occurrences of the substring
    return np.sum(np.char.count(arr, substring))

# Example array
arr = np.array(['hello', 'world', 'hello', 'numpy', 'hello'])

# Specify the substring to count
substring = 'hello'

# Call the function to count occurrences
count = count_substring_occurrences(arr, substring)

# Print the result
print(f"The substring '{substring}' occurs {count} times in the array.")
The substring 'hello' occurs 3 times in the array.


In [ ]:
# Write a function that extracts uppercase characters from a NumPy array of strings.

arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# import numpy as np

def extract_uppercase(arr):
    """Extract uppercase characters from each string in a NumPy array."""
    # Function to extract uppercase characters from a single string
    def get_uppercase(s):
        return ''.join([char for char in s if char.isupper()])
    
    # Vectorize the function to apply it to each element in the array
    vectorized_get_uppercase = np.vectorize(get_uppercase)
    
    # Apply the vectorized function to the input array
    return vectorized_get_uppercase(arr)

# Example array
arr = np.array(['Hello', 'World', 'OpenAI', 'GPT'])

# Call the function to extract uppercase characters
uppercases = extract_uppercase(arr)

# Print the result
print("Uppercase characters from the array:", uppercases)
Uppercase characters from the array: ['H' 'W' 'OAI' 'GPT']


In [ ]:
#  Write a function that replaces occurrences of a substring in a NumPy array of strings with a new string.
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# import numpy as np

def replace_substring(arr, old, new):
    """Replace occurrences of a substring in a NumPy array of strings with a new string."""
    return np.char.replace(arr, old, new)

# Example array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Specify the substring to replace and the new string
old_substring = 'a'
new_string = 'x'

# Call the function to replace the substring
result = replace_substring(arr, old_substring, new_string)

# Print the result
print("Original array:", arr)
Original array: ['apple' 'banana' 'grape' 'pineapple']
print("Modified array:", result)
Modified array: ['xpplx' 'bxnxnx' 'grxpe' 'pinexpxle']

In [ ]:
# Write a function that concatenates strings in a NumPy array element-wise.
arr1 = np.array(['Hello', 'World'])

arr2 = np.array(['Open', 'AI'])

# import numpy as np

def concatenate_arrays(arr1, arr2):
    """Concatenate strings in two NumPy arrays element-wise."""
    return np.char.add(arr1, arr2)

# Example arrays
arr1 = np.array(['Hello', 'World'])
arr2 = np.array(['Open', 'AI'])

# Call the function to concatenate the arrays
result = concatenate_arrays(arr1, arr2)

# Print the result
print("Concatenated array:", result)
Concatenated array: ['HelloOpen' 'WorldAI']

In [ ]:
# Write a function that finds the length of the longest string in a NumPy array.

arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# import numpy as np

def longest_string_length(arr):
    """Find the length of the longest string in a NumPy array."""
    # Calculate the lengths of the strings in the array
    lengths = np.char.str_len(arr)
    # Return the maximum length
    return np.max(lengths)

# Example array
arr = np.array(['apple', 'banana', 'grape', 'pineapple'])

# Call the function to find the length of the longest string
longest_length = longest_string_length(arr)

# Print the result
print("The length of the longest string is:", longest_length)
The length of the longest string is: 9

In [ ]:
# Create a dataset of 100 random integers between 1 and 1000. Compute the mean, median, variance, and
standard deviation of the dataset using NumPy's functions.

# import numpy as np

# Create a dataset of 100 random integers between 1 and 1000
data = np.random.randint(1, 1001, size=100)

# Compute statistics
mean = np.mean(data)
median = np.median(data)
variance = np.var(data)
std_deviation = np.std(data)

# Print the results
print("Dataset:", data)
Dataset: [423 667 735 ...]  # Example output, actual numbers will differ
print("Mean:", mean)
Mean: 500.5  # Example output
print("Median:", median)
Median: 497.5  # Example output
print("Variance:", variance)
Variance: 84018  # Example output
print("Standard Deviation:", std_deviation)
Standard Deviation: 289.30  # Example output


In [ ]:
# Generate an array of 50 random numbers between 1 and 100. Find the 25th and 75th percentiles of the
dataset.

# import numpy as np

# Generate an array of 50 random numbers between 1 and 100
data = np.random.randint(1, 101, size=50)

# Compute the 25th and 75th percentiles
percentile_25 = np.percentile(data, 25)
percentile_75 = np.percentile(data, 75)

# Print the results
print("Dataset:", data)
Dataset: [45 67 12 ...]  # Example output, actual numbers will differ
print("25th Percentile:", percentile_25)
25th Percentile: 25.0  # Example output
print("75th Percentile:", percentile_75)
75th Percentile: 75.0  # Example output


In [ ]:
# Create two arrays representing two sets of variables. Compute the correlation coefficient between these
arrays using NumPy's `corrcoef` function.

# import numpy as np

# Create two arrays representing two sets of variables
array1 = np.array([10, 20, 30, 40, 50])
array2 = np.array([15, 25, 35, 45, 55])

# Compute the correlation coefficient matrix
correlation_matrix = np.corrcoef(array1, array2)

# Extract the correlation coefficient between the two arrays
correlation_coefficient = correlation_matrix[0, 1]

# Print the results
print("Array 1:", array1)
Array 1: [10 20 30 40 50]
print("Array 2:", array2)
Array 2: [15 25 35 45 55]
print("Correlation Coefficient:", correlation_coefficient)
Correlation Coefficient: 0.9999999999999999


In [ ]:
# Create two matrices and perform matrix multiplication using NumPy's `dot` function.

# import numpy as np

# Create two matrices
matrix1 = np.array([[1, 2, 3],
                     [4, 5, 6]])

matrix2 = np.array([[7, 8],
                     [9, 10],
                     [11, 12]])

# Perform matrix multiplication using np.dot
result = np.dot(matrix1, matrix2)

# Alternatively, you can use the @ operator for matrix multiplication
# result = matrix1 @ matrix2

# Print the results
print("Matrix 1:\n", matrix1)
Matrix 1:
[[1 2 3]
 [4 5 6]]
print("Matrix 2:\n", matrix2)
Matrix 2:
[[ 7  8]
 [ 9 10]
 [11 12]]
print("Result of matrix multiplication:\n", result)
Result of matrix multiplication:
[[ 58  64]
 [139 154]]


In [ ]:
# Create an array of 50 integers between 10 and 1000. Calculate the 10th, 50th (median), and 90th
percentiles along with the first and third quartiles.

# import numpy as np

# Create an array of 50 random integers between 10 and 1000
data = np.random.randint(10, 1001, size=50)

# Calculate percentiles and quartiles
percentile_10 = np.percentile(data, 10)
percentile_50 = np.percentile(data, 50)  # This is the median
percentile_90 = np.percentile(data, 90)
quartile_1 = np.percentile(data, 25)  # First quartile (25th percentile)
quartile_3 = np.percentile(data, 75)  # Third quartile (75th percentile)

# Print the results
print("Dataset:", data)
Dataset: [234 456 789 ...]  # Example output, actual numbers will differ
print("10th Percentile:", percentile_10)
10th Percentile: 100.0  # Example output
print("50th Percentile (Median):", percentile_50)
50th Percentile (Median): 500.0  # Example output
print("90th Percentile:", percentile_90)
90th Percentile: 900.0  # Example output
print("First Quartile (Q1):", quartile_1)
First Quartile (Q1): 250.0  # Example output
print("Third Quartile (Q3):", quartile_3)
Third Quartile (Q3): 750.0  # Example output


In [ ]:
# Create a NumPy array of integers and find the index of a specific element.

# import numpy as np

# Create a NumPy array of integers
array = np.array([10, 20, 30, 40, 50, 60, 70, 80, 90, 100])

# Specify the element you want to find
specific_element = 60

# Find the index of the specific element
index = np.where(array == specific_element)[0]

# Print the results
print("Array:", array)
if index.size > 0:
    print(f"The index of the element {specific_element} is: {index[0]}")
else:
    print(f"The element {specific_element} is not in the array.")
Array: [ 10  20  30  40  50  60  70  80  90 100]
The index of the element 60 is: 5

In [ ]:
# Generate a random NumPy array and sort it in ascending order.

# import numpy as np

# Generate a random NumPy array of integers (for example, between 1 and 100)
array_size = 50
random_array = np.random.randint(1, 101, size=array_size)

# Sort the array in ascending order
sorted_array = np.sort(random_array)

# Print the results
print("Original Array:", random_array)
Original Array: [23 56 12 78 ...]  # Example output, actual numbers will differ
print("Sorted Array:", sorted_array)
Sorted Array: [ 1  2  3 ...]  # Example output, actual sorted numbers


In [ ]:
# Filter elements >20  in the given NumPy array.
arr = np.array([12, 25, 6, 42, 8, 30])

# import numpy as np

# Given NumPy array
arr = np.array([12, 25, 6, 42, 8, 30])

# Filter elements > 20
filtered_elements = arr[arr > 20]

# Print the results
print("Original Array:", arr)
Original Array: [12 25  6 42  8 30]
print("Filtered Elements (>20):", filtered_elements)
Filtered Elements (>20): [25 42 30]


In [ ]:
# Filter elements which are divisible by 3 from a given NumPy array.
arr = np.array([1, 5, 8, 12, 15])


# import numpy as np

# Given NumPy array
arr = np.array([1, 5, 8, 12, 15])

# Filter elements divisible by 3
filtered_elements = arr[arr % 3 == 0]

# Print the results
print("Original Array:", arr)
Original Array: [ 1  5  8 12 15]
print("Filtered Elements (divisible by 3):", filtered_elements)
Filtered Elements (divisible by 3): [12 15]


In [ ]:
# Filter elements which are ≥ 20 and ≤ 40 from a given NumPy array.
arr = np.array([10, 20, 30, 40, 50])

# import numpy as np

# Given NumPy array
arr = np.array([10, 20, 30, 40, 50])

# Filter elements that are ≥ 20 and ≤ 40
filtered_elements = arr[(arr >= 20) & (arr <= 40)]

# Print the results
print("Original Array:", arr)
Original Array: [10 20 30 40 50]
print("Filtered Elements (≥ 20 and ≤ 40):", filtered_elements)
Filtered Elements (≥ 20 and ≤ 40): [20 30 40]


In [ ]:
#  For the given NumPy array, check its byte order using the `dtype` attribute byteorder.
arr = np.array([1, 2, 3])

# import numpy as np

# Given NumPy array
arr = np.array([1, 2, 3])

# Check the byte order
byte_order = arr.dtype.byteorder

# Print the result
print("Byte order of the array:", byte_order)
Byte order of the array: =

In [ ]:
# For the given NumPy array, perform byte swapping in place using `byteswap()`.
arr = np.array([1, 2, 3], dtype=np.int32)

# import numpy as np

# Given NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print original array and its byte order
print("Original Array:", arr)
Original Array: [1 2 3]
print("Byte order before swapping:", arr.dtype.byteorder)
Byte order before swapping: =

# Perform byte swapping in place
arr.byteswap(inplace=True)

# Print the array after byte swapping
print("Array after byte swapping:", arr)
Array after byte swapping: [16777216 33554432 50331648]
print("Byte order after swapping:", arr.dtype.byteorder)
Byte order after swapping: <


In [ ]:
# For the given NumPy array, swap its byte order without modifying the original array using
`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

# import numpy as np

# Given NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original Array:", arr)
Original Array: [1 2 3]
print("Byte order before swapping:", arr.dtype.byteorder)
Byte order before swapping: =

# Swap byte order without modifying the original array
swapped_arr = arr.newbyteorder()

# Print the swapped array
print("Swapped Array:", swapped_arr)
Swapped Array: [16777216 33554432 50331648]
print("Byte order of swapped array:", swapped_arr.dtype.byteorder)
Byte order of swapped array: <

In [ ]:
#  For the given NumPy array and swap its byte order conditionally based on system endianness using
`newbyteorder()`.
arr = np.array([1, 2, 3], dtype=np.int32)

# import numpy as np
import sys

# Given NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original Array:", arr)
Original Array: [1 2 3]
print("Byte order before conditional swapping:", arr.dtype.byteorder)
Byte order before conditional swapping: =

# Check system endianness
if sys.byteorder == 'little':
    # If the system is little-endian, swap the byte order
    swapped_arr = arr.newbyteorder()
else:
    # If the system is big-endian or native, keep the original
    swapped_arr = arr

# Print the swapped array
print("Conditionally Swapped Array:", swapped_arr)
Conditionally Swapped Array: [16777216 33554432 50331648]
print("Byte order of conditionally swapped array:", swapped_arr.dtype.byteorder)
Byte order of conditionally swapped array: <


In [ ]:
# . For the given NumPy array, check if byte swapping is necessary for the current system using `dtype`
attribute `byteorder`.
arr = np.array([1, 2, 3], dtype=np.int32)

# import numpy as np
import sys

# Given NumPy array with dtype int32
arr = np.array([1, 2, 3], dtype=np.int32)

# Print the original array and its byte order
print("Original Array:", arr)
Original Array: [1 2 3]
print("Byte order before checking:", arr.dtype.byteorder)
Byte order before checking: =

# Check if byte swapping is necessary
if (arr.dtype.byteorder == '<' and sys.byteorder == 'big') or (arr.dtype.byteorder == '>' and sys.byteorder == 'little'):
    print("Byte swapping is necessary for the current system.")
else:
    print("Byte swapping is not necessary for the current system.")
    Byte swapping is not necessary for the current system.
    
    Notes
The byte order of the array is represented as:
'<': Little-endian.
'>': Big-endian.
'=': Native byte order (same as the system's).


In [ ]:
#  Create a NumPy array `arr1` with values from 1 to 10. Create a copy of `arr1` named `copy_arr` and modify
an element in `copy_arr`. Check if modifying `copy_arr` affects `arr1`.

# import numpy as np

# Create a NumPy array arr1 with values from 1 to 10
arr1 = np.array(range(1, 11))

# Create a copy of arr1 named copy_arr
copy_arr = arr1.copy()

# Modify an element in copy_arr
copy_arr[0] = 100  # Changing the first element to 100

# Print both arrays
print("Original Array (arr1):", arr1)
Original Array (arr1): [ 1  2  3  4  5  6  7  8  9 10]
print("Modified Copy Array (copy_arr):", copy_arr)
Modified Copy Array (copy_arr): [100   2   3   4   5   6   7   8   9  10]

# Check if modifying copy_arr affects arr1
if np.array_equal(arr1, copy_arr):
    print("Modifying copy_arr affects arr1.")
else:
    print("Modifying copy_arr does NOT affect arr1.")
    Modifying copy_arr does NOT affect arr1.

In [ ]:
# Create a 2D NumPy array `matrix` of shape (3, 3) with random integers. Extract a slice `view_slice` from
the matrix. Modify an element in `view_slice` and observe if it changes the original `matrix`.

# import numpy as np

# Create a 3x3 NumPy array with random integers (between 0 and 9)
matrix = np.random.randint(0, 10, size=(3, 3))

# Print the original matrix
print("Original Matrix:\n", matrix)
Original Matrix:
[[3 5 1]
 [2 8 6]
 [4 7 0]]


# Extract a slice from the matrix (e.g., the first two rows and columns)
view_slice = matrix[0:2, 0:2]

# Print the view slice
print("View Slice Before Modification:\n", view_slice)
View Slice Before Modification:
[[3 5]
 [2 8]]

# Modify an element in view_slice
view_slice[0, 0] = 100

# Print the modified view and the original matrix
print("Modified View Slice:\n", view_slice)
Modified View Slice:
[[100   5]
 [  2   8]]
print("Original Matrix After Modification:\n", matrix)
Original Matrix After Modification:
[[100   5   1]
 [  2   8   6]
 [  4   7   0]]


In [ ]:
# Create a NumPy array `array_a` of shape (4, 3) with sequential integers from 1 to 12. Extract a slice
`view_b` from `array_a` and broadcast the addition of 5 to view_b. Check if it alters the original `array_a`.

# import numpy as np

# Create a 4x3 NumPy array with sequential integers from 1 to 12
array_a = np.arange(1, 13).reshape(4, 3)

# Print the original array
print("Original Array (array_a):\n", array_a)
Original Array (array_a):
[[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


# Extract a slice from array_a (e.g., the first two rows and columns)
view_b = array_a[0:2, 0:2]

# Print the view slice
print("View Slice (view_b) Before Modification:\n", view_b)
View Slice (view_b) Before Modification:
[[1 2]
 [4 5]]

# Broadcast the addition of 5 to view_b
view_b += 5

# Print the modified view and the original array
print("Modified View Slice (view_b):\n", view_b)
Modified View Slice (view_b):
[[ 6  7]
 [ 9 10]]
print("Original Array (array_a) After Modification:\n", array_a)
Original Array (array_a) After Modification:
[[ 6  7  3]
 [ 9 10  6]
 [ 7  8  9]
 [10 11 12]]

In [ ]:
# Create a NumPy array `orig_array` of shape (2, 4) with values from 1 to 8. Create a reshaped view
`reshaped_view` of shape (4, 2) from orig_array. Modify an element in `reshaped_view` and check if it
reflects changes in the original `orig_array`.

# import numpy as np

# Create a 2x4 NumPy array with values from 1 to 8
orig_array = np.arange(1, 9).reshape(2, 4)

# Print the original array
print("Original Array (orig_array):\n", orig_array)
Original Array (orig_array):
[[1 2 3 4]
 [5 6 7 8]]


# Create a reshaped view (4, 2) from orig_array
reshaped_view = orig_array.reshape(4, 2)

# Print the reshaped view
print("Reshaped View (reshaped_view) Before Modification:\n", reshaped_view)
Reshaped View (reshaped_view) Before Modification:
[[1 2]
 [3 4]
 [5 6]
 [7 8]]

# Modify an element in the reshaped view
reshaped_view[1, 0] = 100  # Changing the element at row 1, column 0

# Print the modified view and the original array
print("Modified Reshaped View (reshaped_view):\n", reshaped_view)
Modified Reshaped View (reshaped_view):
[[  1   2]
 [100   4]
 [  5   6]
 [  7   8]]

print("Original Array (orig_array) After Modification:\n", orig_array)
Original Array (orig_array) After Modification:
[[  1   2   3   4]
 [100   5   6   7]]


In [ ]:
# Create a NumPy array `data` of shape (3, 4) with random integers. Extract a copy `data_copy` of
elements greater than 5. Modify an element in `data_copy` and verify if it affects the original `data`.

# import numpy as np

# Create a 3x4 NumPy array with random integers between 0 and 10
data = np.random.randint(0, 10, size=(3, 4))

# Print the original array
print("Original Array (data):\n", data)
Original Array (data):
[[3 5 9 1]
 [7 4 6 8]
 [1 0 3 2]]


# Extract a copy of elements greater than 5
data_copy = data[data > 5].copy()

# Print the copy of elements greater than 5
print("Copy of Elements Greater Than 5 (data_copy):\n", data_copy)
Copy of Elements Greater Than 5 (data_copy):
[9 7 6 8]

# Modify an element in the data_copy
if data_copy.size > 0:  # Ensure there is at least one element to modify
    data_copy[0] = 100  # Modify the first element

# Print the modified copy and the original array
print("Modified Copy (data_copy):\n", data_copy)
Modified Copy (data_copy):
[100  7   6   8]
print("Original Array (data) After Modification:\n", data)
Original Array (data) After Modification:
[[3 5 9 1]
 [7 4 6 8]
 [1 0 3 2]]


In [ ]:
# Create two matrices A and B of identical shape containing integers and perform addition and subtraction
operations between them.

# import numpy as np

# Create two matrices A and B of shape (3, 4) with random integers
A = np.random.randint(1, 10, size=(3, 4))  # Random integers between 1 and 9
B = np.random.randint(1, 10, size=(3, 4))  # Random integers between 1 and 9

# Print the two matrices
print("Matrix A:\n", A)
Matrix A:
[[5 2 6 3]
 [1 7 9 4]
 [8 3 5 2]]

print("Matrix B:\n", B)
Matrix B:
[[3 4 1 8]
 [7 2 6 5]
 [1 9 2 4]]


# Perform addition
C_add = A + B

# Perform subtraction
C_sub = A - B

# Print the results of addition and subtraction
print("Addition of A and B (C_add):\n", C_add)
Addition of A and B (C_add):
[[ 8  6  7 11]
 [ 8  9 15  9]
 [ 9 12  7  6]]

print("Subtraction of A and B (C_sub):\n", C_sub)
Subtraction of A and B (C_sub):
[[ 2 -2  5 -5]
 [-6  5  3 -1]
 [ 7 -6  3 -2]]


In [ ]:
# Generate two matrices `C` (3x2) and `D` (2x4) and perform matrix multiplication.

# import numpy as np

# Generate matrix C (3x2) with random integers
C = np.random.randint(1, 10, size=(3, 2))  # Values between 1 and 9

# Generate matrix D (2x4) with random integers
D = np.random.randint(1, 10, size=(2, 4))  # Values between 1 and 9

# Print the generated matrices
print("Matrix C (3x2):\n", C)
Matrix C (3x2):
[[3 7]
 [5 1]
 [4 6]]

print("Matrix D (2x4):\n", D)
Matrix D (2x4):
[[8 7 6 4]
 [5 3 1 9]]

# Perform matrix multiplication
result = C @ D  # Alternatively, you can use np.dot(C, D)

# Print the result of the matrix multiplication
print("Result of C * D:\n", result)
Result of C * D:
[[  61  66  57  73]
 [  50  58  36  68]
 [  54  58  36  66]]


In [ ]:
# Create a matrix `E` and find its transpose.

# import numpy as np

# Create a matrix E (for example, 3x4 matrix)
E = np.random.randint(1, 10, size=(3, 4))  # Random integers between 1 and 9

# Print the original matrix E
print("Matrix E:\n", E)
Matrix E:
[[2 4 7 1]
 [8 3 5 6]
 [9 2 8 4]]


# Find the transpose of matrix E
E_transpose = E.T  # Alternatively, you could use np.transpose(E)

# Print the transposed matrix
print("Transpose of Matrix E:\n", E_transpose)
Transpose of Matrix E:
[[2 8 9]
 [4 3 2]
 [7 5 8]
 [1 6 4]]


In [ ]:
# Generate a square matrix `F` and compute its determinant.

# import numpy as np

# Generate a square matrix F (e.g., 3x3)
F = np.random.randint(1, 10, size=(3, 3))  # Random integers between 1 and 9

# Print the generated matrix F
print("Matrix F:\n", F)
Matrix F:
[[4 5 6]
 [1 3 9]
 [2 8 7]]


# Compute the determinant of matrix F
determinant_F = np.linalg.det(F)

# Print the determinant
print("Determinant of Matrix F:", determinant_F)
Determinant of Matrix F: -22.000000000000004


In [ ]:
# Create a square matrix `G` and find its inverse.

# import numpy as np

# Generate a square matrix G (e.g., 3x3)
G = np.random.randint(1, 10, size=(3, 3))  # Random integers between 1 and 9

# Print the generated matrix G
print("Matrix G:\n", G)
Matrix G:
[[1 2 3]
 [0 1 4]
 [5 6 0]]


# Compute the determinant of G to check if it's invertible
determinant_G = np.linalg.det(G)

if determinant_G != 0:
    # If the matrix is invertible, calculate its inverse
    inverse_G = np.linalg.inv(G)
    print("Inverse of Matrix G:\n", inverse_G)
else:
    print("Matrix G is not invertible (determinant is zero).")
    Inverse of Matrix G:
[[-24.  18.   5.]
 [  5.  -4.  -1.]
 [  6.  -5.   1.]]
